Day 3 – NumPy Deep Dive (Accelerated, DS-Focused)
1.	Strengthen your intuition for:
•	Arrays, shapes, broadcasting
•	Vectorized operations (no Python loops where possible)
2.	Practice common data-science patterns with NumPy:
•	Normalization, scaling
•	Distance computations
•	Basic linear algebra (dot products, matrix multiply)
3.	Implement small but meaningful DS-style utilities using NumPy.

In [1]:
import os
from pathlib import Path

print("CWD:", os.getcwd())
print("Last part of path:", Path.cwd().name)

# Current CWD is .../week01/notebooks
# We want to move up one level to .../week01
week01_root = Path.cwd().parent
os.chdir(week01_root)

print("New CWD:", os.getcwd())
print("Last path part:", Path.cwd().name)

import scripts.data_utils as du
print("data_utils imported from:", du.__file__)

import numpy as np
print("NumPy version:", np.__version__)


CWD: /Users/tarun/tarun/genai/code/gen-ai-test/week01/notebooks
Last part of path: notebooks
New CWD: /Users/tarun/tarun/genai/code/gen-ai-test/week01
Last path part: week01
data_utils imported from: /Users/tarun/tarun/genai/code/gen-ai-test/week01/scripts/data_utils.py
NumPy version: 2.5.2


import numpy as np

Arrays and shapes
a = np.array([1, 2, 3])          # shape: (3,)
b = np.array([[1, 2], [3, 4]])   # shape: (2, 2)

arr.shape  – dimensions
arr.ndim  – number of axes
arr.dtype  – data type

Reshaping
x = np.arange(6)           # [0 1 2 3 4 5]
x2 = x.reshape(2, 3)       # 2 rows, 3 columns

Vectorized operations
x = np.array([1, 2, 3, 4])
y = x ** 2          # elementwise square
z = x + y           # elementwise add

Boolean masks
mask = x > 2        # [False, False, True, True]
x[mask]             # [3, 4]

Broadcasting - stretching smaller arrays to large ones
x = np.array([[1, 2, 3],
              [4, 5, 6]])   # shape (2, 3)

x + 10 # adds 10 to every element

x + np.array([10, 20, 30])  # shape (3,) # adds [10,20,30] to each row

Dimensions are aligned from right to left.
Dimensions are compatible if they are equal or one of them is 1.



x = np.array([1, 2, 3, 4, 5], dtype=float)
mean = x.mean()
std = x.std()
x_norm = (x - mean) / std

Min-max scaling
x_minmax = (x - x.min()) / (x.max() - x.min())

dot product
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a @ b              # dot product (scalar)
np.dot(a, b)       # same

matrix multiplication
A = np.random.randn(3, 4)
B = np.random.randn(4, 2)
A @ B              # matrix multiply (3,2)





In [16]:
pip install numpy pandas matplotlib seaborn jupyterlab scikit-learn

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 7.2 MB/s  0:00:01 eta 0:00:01m
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.5/20.5 MB 775.7 kB/s  0:00:26 eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6/6 [scikit-learn] [scikit-learn]

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


Normalization (Zero Mean, Unit Variance)

For each feature (column), transform values so that:
•	Mean = 0
•	Standard deviation = 1
Formula for each element x in a feature column:
x_norm = x - mu/sigma
where:
•	mu = mean of that feature
•	sigma = standard deviation of that feature

In [2]:
import numpy as np

# Suppose we have 5 samples, 1 feature
x = np.array([1, 2, 3, 4, 5], dtype=float)

mean = x.mean()
std = x.std()

x_norm = (x - mean) / std

print("Original:", x)
print("Mean:", mean)
print("Std:", std)
print("Normalized:", x_norm)
print("Normalized mean:", x_norm.mean())
print("Normalized std:", x_norm.std())

#2d array
X = np.array([
    [1.0, 10.0],
    [2.0, 20.0],
    [3.0, 30.0],
    [4.0, 40.0],
    [5.0, 50.0],
])  # shape (5, 2) → 5 samples, 2 features
mean = X.mean(axis=0)   # shape (2,)
std = X.std(axis=0)     # shape (2,)

X_norm = (X - mean) / std

print("2d Mean per feature:", mean)
print("2d Std per feature:", std)
print("2d Normalized X:\n", X_norm)
print("2d Normalized mean per feature:", X_norm.mean(axis=0))
print("2d Normalized std per feature:", X_norm.std(axis=0))



Original: [1. 2. 3. 4. 5.]
Mean: 3.0
Std: 1.4142135623730951
Normalized: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
Normalized mean: 0.0
Normalized std: 0.9999999999999999
2d Mean per feature: [ 3. 30.]
2d Std per feature: [ 1.41421356 14.14213562]
2d Normalized X:
 [[-1.41421356 -1.41421356]
 [-0.70710678 -0.70710678]
 [ 0.          0.        ]
 [ 0.70710678  0.70710678]
 [ 1.41421356  1.41421356]]
2d Normalized mean per feature: [0. 0.]
2d Normalized std per feature: [1. 1.]


Min - Max Scaling

Scale each feature so that:
Minimum value → 0, Maximum value → 1

x_scaled = x - x_min / x_max - x_min


In [3]:
x = np.array([1, 2, 3, 4, 5], dtype=float)

x_min = x.min()
x_max = x.max()

x_minmax = (x - x_min) / (x_max - x_min)

print("Original:", x)
print("Min:", x_min, "Max:", x_max)
print("Scaled:", x_minmax)
print("Scaled min:", x_minmax.min(), "Scaled max:", x_minmax.max())

#2d array
X = np.array([
    [1.0, 100.0],
    [2.0, 200.0],
    [3.0, 300.0],
    [4.0, 400.0],
    [5.0, 500.0],
])

X_min = X.min(axis=0)
X_max = X.max(axis=0)
range_ = X_max - X_min

X_scaled = (X - X_min) / range_

print("2d Scaled min per feature:", X_scaled.min(axis=0))
print("2d Scaled max per feature:", X_scaled.max(axis=0))


Original: [1. 2. 3. 4. 5.]
Min: 1.0 Max: 5.0
Scaled: [0.   0.25 0.5  0.75 1.  ]
Scaled min: 0.0 Scaled max: 1.0
2d Scaled min per feature: [0. 0.]
2d Scaled max per feature: [1. 1.]


Dot Product & Matrix Multiplication

These are the backbone of linear models, neural nets, and many ML algorithms.

Dot Product of Two Vectors

For vectors a,b 
            n
    a.b =       a_i b_i
            i=1

In [4]:
a = np.array([1, 2, 3], dtype=float)
b = np.array([4, 5, 6], dtype=float)

dot_ab = a @ b          # or np.dot(a, b)
print("a · b =", dot_ab)

# Manual check:
manual = (1*4) + (2*5) + (3*6)
print("Manual:", manual)


a · b = 32.0
Manual: 32


In [5]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
])  # shape (2, 3)

x = np.array([1, 0, -1], dtype=float)  # shape (3,)

y = A @ x  # shape (2,)

print("A:\n", A)
print("x:", x)
print("A @ x:", y)

# Manual:
# row 0: 1*1 + 2*0 + 3*(-1) = -2
# row 1: 4*1 + 5*0 + 6*(-1) = -2


A:
 [[1 2 3]
 [4 5 6]]
x: [ 1.  0. -1.]
A @ x: [-2. -2.]


In [6]:
A = np.random.randint(0, 10, size=(3, 4))  # (3, 4)
B = np.random.randint(0, 10, size=(4, 2))  # (4, 2)

C = A @ B                  # (3, 2)
print("A:\n", A)
print("B:\n", B)
print("C:\n", C)
print("A shape:", A.shape)
print("B shape:", B.shape)
print("C shape:", C.shape)


A:
 [[2 9 0 9]
 [9 3 1 3]
 [7 7 4 1]]
B:
 [[4 6]
 [2 6]
 [7 4]
 [1 0]]
C:
 [[ 35  66]
 [ 52  76]
 [ 71 100]]
A shape: (3, 4)
B shape: (4, 2)
C shape: (3, 2)


Pairwise Squared Distances (Vectorized)
This is a more advanced but very useful pattern.
Problem
Given n points in d dimensions:
•	X is shape  (n, d) 
•	Each row X[i] is a point.
We want a distance matrix D of shape  (n, n)  where:
D[i,j] = ||Xi - Xj||^2
      
       = Xi^2 + Xj^2 - 2.Xi.Xj

Loops:
n = X.shape[0]
D = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        diff = X[i] - X[j]
        D[i, j] = np.sum(diff ** 2)




In [7]:
X = np.array([
    [0.0, 0.0],
    [1.0, 0.0],
    [0.0, 1.0],
    [1.0, 1.0],
])  # 4 points in 2D

norms = np.sum(X**2, axis=1)          # shape (4,)
D = norms[:, None] + norms[None, :] - 2 * (X @ X.T)

# Fix tiny negative values from numerical errors
D = np.maximum(D, 0.0)

print("Points:\n", X)
print("Norms:", norms)
print("Pairwise squared distances:\n", D)


Points:
 [[0. 0.]
 [1. 0.]
 [0. 1.]
 [1. 1.]]
Norms: [0. 1. 1. 2.]
Pairwise squared distances:
 [[0. 1. 1. 2.]
 [1. 0. 2. 1.]
 [1. 2. 0. 1.]
 [2. 1. 1. 0.]]


In [16]:
#Exercise 1 – Shapes, Reshaping, Indexing

import numpy as np

x = np.arange(1, 13)  # 1..12

#Reshape to  (3, 4)  → call it X 
X = x.reshape(3, 4)
print("X:\n", X)
print("Shape of X:", X.shape)
print("Number of dimensions of X:", X.ndim)
print("Size of X:", X.size)
print("Data type of X:", X.dtype)

#Extract first row of X
first_row = X[0, :]
print("First row of X:", first_row)
#Extract last column of X
last_column = X[:, -1]
print("Last column of X:", last_column)
#create a submatrix of x with rows 0-1, cols 1-2
submatrix = X[0:2, 1:3]
print("Submatrix (rows 0-1, cols 1-2):\n", submatrix)
#set all elements greater than 6 to 99
X[X > 6] = 99
print("X after setting elements > 6 to 99:\n", X)

Y = np.arange(24).reshape(2, 3, 4)
print("Y:\n", Y)

print("Shape of Y:", Y.shape)
print("Number of dimensions of Y:", Y.ndim)
print("Size of Y:", Y.size)

#Extract all elements where first_dimension = 1, second_dimension = 0
elements = Y[1, 0, :]
print("Elements where first_dimension = 1, second_dimension = 0:", elements)

#slice - where first 2 rows of the second "block"
slice = Y[1, :2, :]
print("Slice of Y (first 2 rows of second block):\n", slice)

X:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape of X: (3, 4)
Number of dimensions of X: 2
Size of X: 12
Data type of X: int64
First row of X: [1 2 3 4]
Last column of X: [ 4  8 12]
Submatrix (rows 0-1, cols 1-2):
 [[2 3]
 [6 7]]
X after setting elements > 6 to 99:
 [[ 1  2  3  4]
 [ 5  6 99 99]
 [99 99 99 99]]
Y:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Shape of Y: (2, 3, 4)
Number of dimensions of Y: 3
Size of Y: 24
Elements where first_dimension = 1, second_dimension = 0: [12 13 14 15]
Slice of Y (first 2 rows of second block):
 [[12 13 14 15]
 [16 17 18 19]]


In [18]:
#Exercise 2 – Broadcasting & Vectorization

A = np.array([[1, 2, 3],
              [4, 5, 6]])  # shape (2, 3)

b = np.array([10, 20, 30])  # shape (3,)

A_plus_b = A + b
print("A + b:\n", A_plus_b)

row_factors = np.array([2, 3])[:, None]  # shape (2,1)
print("Row factors:\n", row_factors)
A_scaled = A * row_factors
print("A scaled by row factors:\n", A_scaled)

#compute row-wise sum of A
row_sum = A.sum(axis=1)  
print("Row-wise sum of A:", row_sum)
#compute column-wise sum of A
col_sum = A.sum(axis=0)
print("Column-wise sum of A:", col_sum)
#compute row-wise mean of A
row_mean = A.mean(axis=1)
print("Row-wise mean of A:", row_mean)
#compute column-wise mean of A
col_mean = A.mean(axis=0)
print("Column-wise mean of A:", col_mean)

x = np.linspace(0, 10, 100)  # 100 points from 0 to 10
sin_x = np.sin(x)
cos_x = np.cos(x)
check = sin_x**2 + cos_x**2
print("Check sin^2 + cos^2 (should be close to 1):", check)
print("check min:", check.min())
print("check max:", check.max())


A + b:
 [[11 22 33]
 [14 25 36]]
Row factors:
 [[2]
 [3]]
A scaled by row factors:
 [[ 2  4  6]
 [12 15 18]]
Row-wise sum of A: [ 6 15]
Column-wise sum of A: [5 7 9]
Row-wise mean of A: [2. 5.]
Column-wise mean of A: [2.5 3.5 4.5]
Check sin^2 + cos^2 (should be close to 1): [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]
check min: 0.9999999999999998
check max: 1.0000000000000002


In [3]:
#Exercise 3 - Normalization

import importlib
import scripts.np_utils as nu

importlib.reload(nu)

from scripts.np_utils import normalize_zero_mean_unit_var, scale_minmax, pairwise_squared_distances

# Example data
X = np.random.randn(20, 3)  # 20 samples, 3 features

X_norm = normalize_zero_mean_unit_var(X)
X_scaled = scale_minmax(X, 0, 1)

print("Original mean (per col):", X.mean(axis=0))
print("Normalized mean (per col):", X_norm.mean(axis=0))
print("Normalized std (per col):", X_norm.std(axis=0))

print("Scaled min (per col):", X_scaled.min(axis=0))
print("Scaled max (per col):", X_scaled.max(axis=0))


2026-09-06 18:24:35,822 [INFO] Normalizing array of shape (20, 3)
2026-09-06 18:24:35,823 [INFO] Min-max scaling array of shape (20, 3) to [0, 1]


Original mean (per col): [-0.2145098   0.06898177 -0.17771724]
Normalized mean (per col): [-4.99600361e-17 -1.66533454e-17  1.73472348e-18]
Normalized std (per col): [1. 1. 1.]
Scaled min (per col): [0. 0. 0.]
Scaled max (per col): [1. 1. 1.]


In [7]:
#Exercise 4 – Pairwise Squared Distances

# Exercise 4 – Pairwise squared distances

import numpy as np
from scripts.np_utils import pairwise_squared_distances

X_small = np.array([
    [0.0, 0.0],
    [1.0, 0.0],
    [0.0, 1.0],
    [1.0, 1.0],
])

D = pairwise_squared_distances(X_small)

print("Input points:\n", X_small)
print("Distance matrix:\n", D)
print("Distance matrix shape:", D.shape)


#manual check
manual_distance = np.sum((X_small[0] - X_small[3]) ** 2)

print("D[0, 3]:", D[0, 3])
print("Manual distance:", manual_distance)





2026-09-06 18:29:38,131 [INFO] Computing pairwise squared distances for array of shape (4, 2)


Input points:
 [[0. 0.]
 [1. 0.]
 [0. 1.]
 [1. 1.]]
Distance matrix:
 [[0. 1. 1. 2.]
 [1. 0. 2. 1.]
 [1. 2. 0. 1.]
 [2. 1. 1. 0.]]
Distance matrix shape: (4, 4)
D[0, 3]: 2.0
Manual distance: 2.0


## Exercise 5 – Linear Regression with NumPy

We will generate synthetic data using a known weight vector, estimate the weights from the data, and evaluate the predictions using mean squared error.

In [10]:
#Exercise 5 - Linear Regression with NumPy

#Step 1 - Generate data for regression

np.random.seed(27)

n = 100
X = np.random.randn(n, 3)

true_w = np.array([1.5, -2.0, 0.5])

noise = 0.5 * np.random.randn(n)
y = X @ true_w + noise

print("X shape:", X.shape)
print("y shape:", y.shape)
print("True weights:", true_w)



X shape: (100, 3)
y shape: (100,)
True weights: [ 1.5 -2.   0.5]


In [12]:
from scripts.ml_utils import train_test_split_simple

X_train, X_test, y_train, y_test = train_test_split_simple(X,y,test_ratio=0.2)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)


2026-09-06 18:36:56,417 [INFO] train_test_split_simple: n=100, n_train=80, n_test=20


X_train shape: (80, 3)
X_test shape: (20, 3)
y_train shape: (80,)
y_test shape: (20,)


Weights = Inverse(X_Transpose . X).X_Transpose.y

In [13]:
def fit_linear_regression(X: np.ndarray,y: np.ndarray) -> np.ndarray:
    """
    Fit linear regression using the normal equation.

    Returns:
        Estimated weight vector.
    """
    X_transpose = X.T
    weights = np.linalg.inv(X_transpose @ X) @ X_transpose @ y
    return weights

def predict(X: np.ndarray,weights: np.ndarray) -> np.ndarray:
    """Generate predictions using X and the learned weights."""
    return X @ weights

def mean_squared_error_np(y_true: np.ndarray,y_pred: np.ndarray) -> float:
    """Return mean squared error between true and predicted values."""
    return float(np.mean((y_true - y_pred) ** 2))

learned_weights = fit_linear_regression(X_train, y_train)

y_train_pred = predict(X_train, learned_weights)
y_test_pred = predict(X_test, learned_weights)

train_mse = mean_squared_error_np(y_train, y_train_pred)
test_mse = mean_squared_error_np(y_test, y_test_pred)

print("True weights:   ", true_w)
print("Learned weights: ", learned_weights)
print("Train MSE:", train_mse)
print("Test MSE:", test_mse)



True weights:    [ 1.5 -2.   0.5]
Learned weights:  [ 1.51114079 -1.92161079  0.55233402]
Train MSE: 0.2666702526549124
Test MSE: 0.18905944417133974


In [19]:
#alternate methods for computing linear regression weights

# Fit with NumPy least squares
w_lstsq, residuals, rank, s = np.linalg.lstsq(X, y, rcond=None)

print("lstsq weights:", w_lstsq)

# Predictions and MSE
y_pred_lstsq = X @ w_lstsq
mse_lstsq = float(np.mean((y - y_pred_lstsq) ** 2))
print("lstsq MSE:", mse_lstsq)



lstsq weights: [ 1.51634579 -1.97632224  0.56095197]
lstsq MSE: 0.24866986380846462


Linear Regression: yp = X.w + b(intercept)

In our first case, we generated:

 y = X.true_w + noise

In [20]:
#using sklearn's LinearRegression
from sklearn.linear_model import LinearRegression

# Create and fit the model
model = LinearRegression()          # by default, fit_intercept=True
model.fit(X, y)

w_sk = model.coef_                  # shape (3,)
b_sk = model.intercept_             # scalar

print("sklearn weights:", w_sk)
print("sklearn intercept:", b_sk)

# Predictions and MSE
y_pred_sk = model.predict(X)
mse_sk = float(np.mean((y - y_pred_sk) ** 2))
print("sklearn MSE:", mse_sk)


sklearn weights: [ 1.51733987 -1.97726452  0.56145146]
sklearn intercept: -0.01331018962476263
sklearn MSE: 0.24849454662268883


In [21]:
#LinearRegression with fit_intercept=False
model_no_bias = LinearRegression(fit_intercept=False)
model_no_bias.fit(X, y)

w_no_bias = model_no_bias.coef_
y_pred_no_bias = model_no_bias.predict(X)
mse_no_bias = float(np.mean((y - y_pred_no_bias) ** 2))

print("sklearn (no intercept) weights:", w_no_bias)
print("sklearn (no intercept) MSE:", mse_no_bias)


sklearn (no intercept) weights: [ 1.51634579 -1.97632224  0.56095197]
sklearn (no intercept) MSE: 0.24866986380846462


In [22]:
# True weights
print("True weights:     ", true_w)

# lstsq
print("lstsq weights:    ", w_lstsq)

# sklearn with intercept
print("sklearn weights:  ", w_sk)
print("sklearn intercept:", b_sk)

# sklearn without intercept
print("sklearn (no bias) weights:", w_no_bias)


True weights:      [ 1.5 -2.   0.5]
lstsq weights:     [ 1.51634579 -1.97632224  0.56095197]
sklearn weights:   [ 1.51733987 -1.97726452  0.56145146]
sklearn intercept: -0.01331018962476263
sklearn (no bias) weights: [ 1.51634579 -1.97632224  0.56095197]
